/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package first;

import java.sql.*;

public class App {
    public String getGreeting() throws Exception {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        // System.out.println(new App().getGreeting());
        System.out.println("Driver loaded");
        Connection conn;
        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/test", "postgres", "sudam");

        System.out.println("Coonection done");

        Statement stmt;
        stmt = conn.createStatement();
        String sql;
        sql = "insert into student values(234,'Patil')";
        stmt.executeUpdate(sql);
        System.out.println("record inserted");

        conn.close();

    }
}
